(self.AMP=self.AMP||[]).push({n:"amp-sidebar",v:"2008220050001",f:(function(AMP,_){
var g,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ba(this);"function"===typeof Symbol&&Symbol("x");var n;
if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var p;a:{var ca={a:!0},q={};try{q.__proto__=ca;p=q.a;break a}catch(a){}p=!1}n=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=n;
function t(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(r)r(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ua=b.prototype};function u(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var da=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function ea(a){return a?Array.prototype.slice.call(a):[]};var v=self.AMP_CONFIG||{},fa=("string"==typeof v.cdnProxyRegex?new RegExp(v.cdnProxyRegex):v.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function ha(a){if(self.document&&self.document.head&&(!self.location||!fa.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}v.cdnUrl||ha("runtime-host");v.geoApiUrl||ha("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var w=self.__AMP_LOG;function x(){if(!w.user)throw Error("failed to call initLogConstructor");return w.user};function y(){this.l=null}g=y.prototype;g.add=function(a){var b=this;this.l||(this.l=[]);this.l.push(a);return function(){b.remove(a)}};g.remove=function(a){this.l&&(a=this.l.indexOf(a),-1<a&&this.l.splice(a,1))};g.removeAll=function(){this.l&&(this.l.length=0)};g.fire=function(a){if(this.l)for(var b=this.l,c=0;c<b.length;c++)(0,b[c])(a)};g.getHandlerCount=function(){return this.l?this.l.length:0};function ia(a){var b=a.indexOf("#");return-1==b?a:a.substring(0,b)};function ja(a){if(a.__AMP__EXPERIMENT_TOGGLES)return a.__AMP__EXPERIMENT_TOGGLES;a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);var b=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var c in a.AMP_CONFIG){var d=a.AMP_CONFIG[c];"number"===typeof d&&0<=d&&1>=d&&(b[c]=Math.random()<d)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length){var e=a.AMP_CONFIG["allow-doc-opt-in"],f=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]');
if(f){var h=f.getAttribute("content").split(",");for(c=0;c<h.length;c++)-1!=e.indexOf(h[c])&&(b[h[c]]=!0)}}Object.assign(b,ka(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){c=a.AMP_CONFIG["allow-url-opt-in"];var l=a.location.originalHash||a.location.hash;a=Object.create(null);if(l)for(var k;k=da.exec(l);){var m=u(k[1],k[1]);k=k[2]?u(k[2].replace(/\+/g," "),k[2]):"";a[m]=k}for(l=0;l<c.length;l++)m=a["e-"+c[l]],"1"==m&&(b[c[l]]=!0),"0"==
m&&(b[c[l]]=!1)}return b}function ka(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){if(w.dev)a=w.dev;else throw Error("failed to call initLogConstructor");a.warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};function la(a,b){var c=a.ownerDocument.defaultView,d=c.__AMP_TOP||(c.__AMP_TOP=c),e=c!=d,f=!!ja(d)["ampdoc-fie"];e&&!f?b=z(c,b)?A(c,b):null:(a=B(a),a=ma(a),b=z(a,b)?A(a,b):null);return b}function C(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return A(a,b)}function D(a,b){var c=B(a);c=ma(c);return A(c,b)}function B(a){return a.nodeType?C((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function ma(a){a=B(a);return a.isSingleDoc()?a.win:a}
function A(a,b){z(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function z(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)};var na;/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var E;function oa(a){return":not([toolbar]) [autoscroll]".replace(/^|,/g,"$&"+a+" ")};function qa(a){if(void 0===a.isConnected){do if(a=ra(a),a.host)a=a.host;else break;while(1)}}function ra(a){if(Node.prototype.getRootNode)return a.getRootNode()||a;for(;a.parentNode&&(!a||"I-AMPHTML-SHADOW-ROOT"!=a.tagName&&(11!=a.nodeType||"[object ShadowRoot]"!==Object.prototype.toString.call(a)));a=a.parentNode);return a}function sa(a,b){for(;a&&void 0!==a;a=a.parentElement)if(b(a))return a;return null}
function F(a,b){return a.closest?a.closest(b):sa(a,function(a){var c=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return c?c.call(a,b):!1})}function ta(a){return"rtl"==(a.body.getAttribute("dir")||a.documentElement.getAttribute("dir")||"ltr")};function G(a,b){var c=this;this.Ca=C(a,"timer");this.Ja=b;this.Ha=0;this.S=-1;this.fa=0;this.la=!1;this.Ga=function(){c.$()}}G.prototype.isPending=function(){return-1!=this.S};G.prototype.schedule=function(a){var b=a||this.Ha;this.la&&10>b&&(b=10);var c=Date.now()+b;return!this.isPending()||-10>c-this.fa?(this.cancel(),this.fa=c,this.S=this.Ca.delay(this.Ga,b),!0):!1};G.prototype.$=function(){this.S=-1;this.fa=0;this.la=!0;this.Ja();this.la=!1};
G.prototype.cancel=function(){this.isPending()&&(this.Ca.cancel(this.S),this.S=-1)};function ua(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};var H;function va(a){if(void 0!==H)return H;H=!1;try{var b={get passive(){H=!0;return!1}};a.addEventListener("test-options",null,b);a.removeEventListener("test-options",null,b)}catch(c){}return H};function wa(a,b,c,d){this.type=a;this.data=b;this.time=c;this.event=d}
function xa(a,b,c){this.o=a;this.c=[];this.K=[];this.m=[];this.h=[];this.j=null;this.Qa=b;this.Ra=c;this.ba=!1;this.$=new G(a.ownerDocument.defaultView,this.wa.bind(this));this.Aa=new y;this.R=Object.create(null);this.ua=this.Oa.bind(this);this.sa=this.Ma.bind(this);this.ta=this.Na.bind(this);this.ra=this.La.bind(this);var d=va(a.ownerDocument.defaultView);this.o.addEventListener("touchstart",this.ua,d?{passive:!0}:!1);this.o.addEventListener("touchend",this.sa);this.o.addEventListener("touchmove",
this.ta,d?{passive:!0}:!1);this.o.addEventListener("touchcancel",this.ra);this.ha=!1}function ya(a){var b=!1,c=!0;b=void 0===b?!1:b;c=void 0===c?!1:c;var d=a.__AMP_Gestures;d||(d=new xa(a,b,c),a.__AMP_Gestures=d);return d}g=xa.prototype;g.cleanup=function(){this.o.removeEventListener("touchstart",this.ua);this.o.removeEventListener("touchend",this.sa);this.o.removeEventListener("touchmove",this.ta);this.o.removeEventListener("touchcancel",this.ra);delete this.o.__AMP_Gestures;this.$.cancel()};
g.onGesture=function(a,b){var c=new a(this),d=c.getType(),e=this.R[d];e||(this.c.push(c),e=new y,this.R[d]=e);return e.add(b)};g.removeGesture=function(a){var b=(new a(this)).getType();if(a=this.R[b]){a.removeAll();a=ua(this.c,function(a){return a.getType()==b});if(0>a)return!1;this.c.splice(a,1);this.m.splice(a,1);this.h.splice(a,1);this.K.splice(a,1);delete this.R[b];return!0}return!1};g.onPointerDown=function(a){return this.Aa.add(a)};
g.Oa=function(a){var b=Date.now();this.ba=!1;this.Aa.fire(a);for(var c=0;c<this.c.length;c++)if(!this.m[c]&&(this.h[c]&&this.h[c]<b&&I(this,c),this.c[c].onTouchStart(a))){var d=c;this.K[d]=!0;this.h[d]=0}J(this,a)};g.Na=function(a){for(var b=Date.now(),c=0;c<this.c.length;c++)this.K[c]&&(this.h[c]&&this.h[c]<b?I(this,c):this.c[c].onTouchMove(a)||I(this,c));J(this,a)};
g.Ma=function(a){for(var b=Date.now(),c=0;c<this.c.length;c++)if(this.K[c])if(this.h[c]&&this.h[c]<b)I(this,c);else{this.c[c].onTouchEnd(a);var d=!this.h[c],e=this.h[c]<b;this.j!=this.c[c]&&(d||e)&&I(this,c)}J(this,a)};g.La=function(a){for(var b=0;b<this.c.length;b++){var c=b;this.m[c]=0;I(this,c)}J(this,a)};
function J(a,b){var c=!!a.j||a.ba;a.ba=!1;if(!c)for(var d=Date.now(),e=0;e<a.c.length;e++)if(a.m[e]||a.h[e]&&a.h[e]>=d){c=!0;break}c?(b.stopPropagation(),a.Qa||b.preventDefault()):a.Ra&&b.stopPropagation();a.ha&&(a.ha=!1,a.wa())}
g.wa=function(){for(var a=Date.now(),b=-1,c=0;c<this.c.length;c++)if(!this.m[c])this.h[c]&&this.h[c]<a&&I(this,c);else if(-1==b||this.m[c]>this.m[b])b=c;if(-1!=b){var d=0;for(c=0;c<this.c.length;c++)!this.m[c]&&this.K[c]&&(d=Math.max(d,this.h[c]-a));if(2>d){a=b;c=this.c[a];for(var e=0;e<this.c.length;e++)if(e!=a){var f=e;this.m[f]=0;I(this,f)}this.m[a]=0;this.h[a]=0;this.j=c;c.acceptStart()}else this.$.schedule(d)}};function I(a,b){a.K[b]=!1;a.h[b]=0;a.m[b]||a.c[b].acceptCancel()}
function K(a,b){this.Ta=a;this.X=b}g=K.prototype;g.getType=function(){return this.Ta};g.signalReady=function(a){var b=this.X;if(b.j)this.acceptCancel();else{for(var c=Date.now(),d=0;d<b.c.length;d++)b.c[d]==this&&(b.m[d]=c+a,b.h[d]=0);b.ha=!0}};g.signalPending=function(a){var b=this.X;if(b.j)this.acceptCancel();else for(var c=Date.now(),d=0;d<b.c.length;d++)b.c[d]==this&&(b.h[d]=c+a)};g.signalEnd=function(){var a=this.X;a.j==this&&(a.j=null,a.ba=!0)};
g.signalEmit=function(a,b){var c=this.X.R[this.getType()];c&&c.fire(new wa(this.getType(),a,Date.now(),b))};g.acceptStart=function(){};g.acceptCancel=function(){};g.onTouchStart=function(){return!1};g.onTouchMove=function(){return!1};g.onTouchEnd=function(){};function za(a,b,c){1>b&&(b=1);var d=.5+Math.min(b/33.34,.5);return a/b*d+c*(1-d)};function L(a,b,c,d){K.call(this,a,b);this.xa=c;this.Fa=d;this.j=!1;this.oa=this.na=this.ia=this.W=this.Ba=this.ka=this.ja=this.F=this.D=this.J=this.I=0}t(L,K);g=L.prototype;g.onTouchStart=function(a){a=a.touches;return this.j&&a&&1<a.length?!0:a&&1==a.length?(this.Ba=Date.now(),this.I=a[0].clientX,this.J=a[0].clientY,!0):!1};
g.onTouchMove=function(a){var b=a.touches;if(b&&1<=b.length){var c=b[0];b=c.clientX;c=c.clientY;this.D=b;this.F=c;if(this.j)M(this,!1,!1,a);else if(a=Math.abs(b-this.I),b=Math.abs(c-this.J),this.xa&&this.Fa)(8<=a||8<=b)&&this.signalReady(-10);else if(this.xa)if(8<=a&&a>b)this.signalReady(-10);else{if(8<=b)return!1}else if(this.Fa)if(8<=b&&b>a)this.signalReady(-10);else{if(8<=a)return!1}else return!1;return!0}return!1};
g.onTouchEnd=function(a){var b=a.touches;b&&0==b.length&&this.j&&(this.j=!1,M(this,!1,!0,a),this.signalEnd())};g.acceptStart=function(){this.j=!0;this.ja=this.I;this.ka=this.J;this.ia=this.Ba;this.I=this.D;this.J=this.F;M(this,!0,!1,null)};g.acceptCancel=function(){this.j=!1};
function M(a,b,c,d){a.W=Date.now();var e=a.W-a.ia;if(!c&&4<e||c&&16<e){var f=za(a.D-a.ja,e,a.na),h=za(a.F-a.ka,e,a.oa);if(!c||32<e||0!=f||0!=h)a.na=1E-4<Math.abs(f)?f:0,a.oa=1E-4<Math.abs(h)?h:0;a.ja=a.D;a.ka=a.F;a.ia=a.W}a.signalEmit({first:b,last:c,time:a.W,deltaX:a.D-a.I,deltaY:a.F-a.J,startX:a.I,startY:a.J,lastX:a.D,lastY:a.F,velocityX:a.na,velocityY:a.oa},d)}function Aa(a){L.call(this,"swipe-x",a,!0,!1)}t(Aa,L);function N(a,b){var c=C(a,"timer");return c.promise(1).then(function(){return c.promise(b)})};var O,Ba="Webkit webkit Moz moz ms O o".split(" ");function P(a,b){for(var c in b){var d=a,e=b[c];var f=d.style;var h=c;if(2>h.length?0:0==h.lastIndexOf("--",0))f=h;else{O||(O=Object.create(null));var l=O[h];if(!l){l=h;if(void 0===f[h]){var k=h;k=k.charAt(0).toUpperCase()+k.slice(1);b:{for(var m=0;m<Ba.length;m++){var pa=Ba[m]+k;if(void 0!==f[pa]){k=pa;break b}}k=""}void 0!==f[k]&&(l=k)}O[h]=l}f=l}f&&((2>f.length?0:0==f.lastIndexOf("--",0))?d.style.setProperty(f,e):d.style[f]=e)}}
function Q(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function R(a,b,c){this.pa=a;this.ea=b;this.Pa=c;this.da="backward";this.P="horizontal";this.Z=this.B=null}function S(a){return"horizontal"==a.P?a.B.offsetWidth:a.B.offsetHeight}function T(a,b,c){b="horizontal"==a.P?b:c;return"backward"==a.da?-Math.min(b,0):Math.max(b,0)}function U(a,b,c){c=void 0===c?"":c;var d="backward"==a.da?-b:b;return"translate("+("horizontal"==a.P?""+d+c:0)+", "+("horizontal"==a.P?0:""+d+c)+")"}
R.prototype.startSwipe=function(a){var b=a.mask,c=a.direction,d=a.orientation;this.B=a.swipeElement;this.Z=b;this.da=c;this.P=d};R.prototype.swipeMove=function(a){Ca(this,a,!1)};R.prototype.endSwipe=function(a){Ca(this,a,!0)};function Da(a,b,c){var d=.75*c;P(a.B,{transform:U(a,b,"px"),transition:d+"ms transform cubic-bezier(0.15, .55, .3, 0.95)"});return N(a.pa,d)}
function Ea(a,b){var c=.8*b;return a.ea(function(){P(a.B,{transform:U(a,0),transition:c+"ms transform ease-in"});P(a.Z,{opacity:"",transition:c+"ms opacity ease-in"})}).then(function(){return N(a.pa,c)})}function Fa(a,b){var c=.75*(S(a)-b);return a.ea(function(){P(a.B,{transform:U(a,100,"%"),transition:c+"ms transform ease-out"});P(a.Z,{opacity:0,transition:c+"ms opacity ease-out"})}).then(function(){return N(a.pa,c)}).then(function(){return a.Pa()})}
function Ga(a,b,c){b=void 0===b?"":b;c=void 0===c?"":c;P(a.B,{transform:b,transition:""});P(a.Z,{opacity:c,transition:""})}function Ha(a,b,c,d,e){var f=T(a,22.5*b+d,22.5*c+e),h=T(a,b,c),l=.5*S(a);return f<l&&.65>h?Da(a,f,h).then(function(){return Ea(a,f)}):Fa(a,f)}function Ca(a,b,c){var d=b.deltaX,e=b.deltaY,f=b.velocityX,h=b.velocityY;a.ea(function(){if(c)Ha(a,f,h,d,e).then(function(){Ga(a)});else{var b=T(a,d,e),k=b/S(a),m=Math.max(0,1-k);Ga(a,U(a,b,"px"),m)}})};function Ia(a,b){if(void 0!==E)var c=E;else{try{var d=b.ownerDocument,e=d.createElement("div"),f=d.createElement("div");e.appendChild(f);c=e.querySelector(":scope div")===f}catch(l){c=!1}c=E=c}c?c=b.querySelector(oa(":scope")):(b.classList.add("i-amphtml-scoped"),c=oa(".i-amphtml-scoped"),c=b.querySelectorAll(c),b.classList.remove("i-amphtml-scoped"),c=void 0===c[0]?null:c[0]);if(c){var h=(a.win.getComputedStyle(b)||Object.create(null))["overflow-y"];"scroll"!=h&&"auto"!=h?x().error("AMP-SIDEBAR",
"for 'autoscroll', 'nav [toolbar]' element must be set to overflow\n        'scroll' or 'auto' for 'autoscroll' to work."):D(a,"viewport").animateScrollWithinParent(c,b,"center",0)}};function Ja(a,b){this.va=b;this.w=a;this.ca=b.getAmpDoc();this.Sa=this.w.getAttribute("toolbar");this.T=null;this.A=void 0;this.aa=!1;this.w.classList.add("amp-sidebar-toolbar-target-hidden");this.T=this.w.cloneNode(!0);a=this.w.getAttribute("toolbar-target");var c=this.w;a=x().assert(a,'"toolbar-target" is required',c,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0);if(c=this.ca.getElementById(a))this.A=c,this.T.classList.add("i-amphtml-toolbar"),Q(this.A,!1);else throw x().createError("Could not find the toolbar-target element with an id: "+
a);}Ja.prototype.onLayoutChange=function(){this.ca.win.matchMedia(this.Sa).matches?Ka(this):La(this)};function Ka(a){a.aa?na||(na=Promise.resolve(void 0)):a.va.mutateElement(function(){a.A&&(Q(a.A,!0),a.A.contains(a.T)||a.A.appendChild(a.T),a.w.classList.add("amp-sidebar-toolbar-target-shown"),a.w.classList.remove("amp-sidebar-toolbar-target-hidden"),a.aa=!0,Ia(a.ca,a.T))})}
function La(a){a.aa&&a.va.mutateElement(function(){a.A&&(Q(a.A,!1),a.w.classList.add("amp-sidebar-toolbar-target-hidden"),a.w.classList.remove("amp-sidebar-toolbar-target-shown"),a.aa=!1)})};var V=[];function Ma(a){var b=[];a=Na(a);for(var c={},d=0;d<a.length;c={M:c.M},d++)c.M=a[d],c.M.parentNode&&ea(c.M.parentNode.children).filter(function(a){return function(b){return b!=a.M}}(c)).forEach(function(a){return b.push(a)});return b}function Na(a){for(var b=[],c=a;c;c=c.parentNode||c.host)b.push(c);return b}
function Oa(a){for(var b=[];a;){a=ra(a);var c=a.querySelectorAll("a[href],area[href],button,details summary,iframe,input,select,textarea,[contenteditable],[draggable],[tabindex]");Array.prototype.push.apply(b,c);a=a.host}return b}
function Pa(a){V.every(function(b){return b.element!==a});qa(a);var b=Ma(a),c=Na(a).filter(function(a){return a.nodeType==Node.ELEMENT_NODE}),d=Oa(a),e=d.filter(function(b){return a.contains(b)&&void 0!==b.__AMP_MODAL_SAVED_TAB_INDEX}),f=d.filter(function(b){return!a.contains(b)&&void 0===b.__AMP_MODAL_SAVED_TAB_INDEX}),h=b.concat(c).map(function(a){return{element:a,prevValue:a.getAttribute("aria-hidden")}});c.forEach(function(a){return a.removeAttribute("aria-hidden")});b.forEach(function(a){return a.setAttribute("aria-hidden",
"true")});f.forEach(function(a){a.__AMP_MODAL_SAVED_TAB_INDEX=a.getAttribute("tabindex");a.setAttribute("tabindex","-1")});e.forEach(function(a){var b=a.__AMP_MODAL_SAVED_TAB_INDEX;null===b?a.removeAttribute("tabindex"):a.setAttribute("tabindex",b)});V.push({element:a,hiddenElementInfos:h,focusableExternalElements:f,focusableInternalElements:e})}
function Qa(a){var b=V.pop(),c=b.hiddenElementInfos,d=b.focusableExternalElements;b=b.focusableInternalElements;qa(a);c.forEach(function(a){var b=a.element,c=a.prevValue;null===c?b.removeAttribute("aria-hidden"):b.setAttribute("aria-hidden",c)});b.forEach(function(a){a.setAttribute("tabindex","-1")});d.forEach(function(a){var b=a.__AMP_MODAL_SAVED_TAB_INDEX;null===b?a.removeAttribute("tabindex"):a.setAttribute("tabindex",b);a.__AMP_MODAL_SAVED_TAB_INDEX=void 0})};function W(a){var b=AMP.BaseElement.call(this,a)||this;b.L=null;b.U=null;b.Ea=null;b.Y=null;b.C=b.win.document;b.Ia=b.C.documentElement;b.H=null;b.Da=[];var c=C(b.win,"platform");b.O=c.isIos();b.Ka=c.isSafari();b.V=-1;b.qa=!1;b.N=null;b.ga=null;b.ya=0;b.G=!1;b.za=null;b.ma=new R(b.win,function(a){return b.mutateElement(a)},function(){return X(b,!0,3)});return b}t(W,AMP.BaseElement);
W.prototype.buildCallback=function(){var a=this,b=this.element;b.classList.add("i-amphtml-overlay");b.classList.add("i-amphtml-scrollable");this.H=b.getAttribute("side");this.L=this.getViewport();this.U=la(b,"action");this.element.parentNode!=this.element.ownerDocument.body&&this.element.parentNode!=this.getAmpDoc().getBody()&&this.user().warn("amp-sidebar toolbar","amp-sidebar toolbar is recommended to be a direct child of the <body> element to preserve a logical DOM order.");"left"!=this.H&&"right"!=
this.H&&(this.H=Ra(this,ta(this.C)?"right":"left"),b.setAttribute("side",this.H));Sa(this);b.addEventListener("amp:dom-update",function(){Sa(a)});this.getAmpDoc().whenReady().then(function(){ea(b.querySelectorAll("nav[toolbar]")).forEach(function(b){try{a.Da.push(new Ja(b,a))}catch(d){a.user().error("amp-sidebar toolbar","Failed to instantiate toolbar",d)}})});this.O&&Ta(this);b.hasAttribute("role")||b.setAttribute("role","menu");b.tabIndex=-1;this.Ia.addEventListener("keydown",function(b){"Escape"==
b.key&&X(a,!1,3)&&b.preventDefault()});this.N=Ua(this);this.N||(this.N=this.createScreenReaderCloseButton(),b.insertBefore(this.N,this.element.firstChild));b.appendChild(this.createScreenReaderCloseButton());this.registerDefaultAction(function(b){Va(a,b.trust,b.caller)},"open");this.registerAction("close",function(b){X(a,!1,b.trust)});this.registerAction("toggle",function(b){var c=b.trust;b=b.caller;a.G?X(a,!1,c):Va(a,c,b)});this.U.addToAllowlist("amp-sidebar",["open","close","toggle"],["email"]);
b.addEventListener("click",function(c){if((c=F(c.target,"A"))&&c.href){var d=la(b,"url").parse(c.href),e=a.getAmpDoc().getUrl();ia(c.href)==ia(e)&&d.hash&&X(a,!1,3)}},!0);Wa(this,this.element)};function Sa(a){if(!a.za){var b=a.element.querySelector("amp-nested-menu");b&&(C(a.win,"extensions").installExtensionForDoc(a.getAmpDoc(),"amp-nested-menu"),a.za=b)}}
function Ua(a){for(var b=a.element.querySelectorAll("[on]"),c=0;c<b.length;c++){var d=b[c],e=a.U.hasResolvableActionForTarget(d,"tap",a.element,d.parentElement),f=F(d,"[toolbar]");if(e&&!f)return d}return null}
W.prototype.createScreenReaderCloseButton=function(){var a=this,b=this.element.getAttribute("data-close-button-aria-label")||"Close the sidebar",c=this.C.createElement("button");c.textContent=b;c.classList.add("i-amphtml-screen-reader");c.tabIndex=-1;c.addEventListener("click",function(){X(a,!1,3)});return c};W.prototype.onLayoutMeasure=function(){var a=this;this.getAmpDoc().whenReady().then(function(){a.Da.forEach(function(a){a.onLayoutChange()})})};
function Y(a,b,c){function d(){a.Ea===b&&a.mutateElement(b)}a.Ea=b;c?C(a.win,"timer").delay(d,c):d()}
function Xa(a,b){Q(a.element,!0);Q(Z(a),!0);a.L.addToFixedLayer(a.element,!0);a.mutateElement(function(){Pa(a.element)});a.O&&a.Ka&&Ya(a);a.element.scrollTop=1;a.element.setAttribute("open","");Z(a).setAttribute("open","");Y(a,function(){var c=a.getRealChildren(),d=D(a.element,"owners");d.scheduleLayout(a.element,c);d.scheduleResume(a.element,c);if(!a.O||!D(a.element,"viewer").isEmbedded())try{a.N.focus()}catch(e){}Za(a,"sidebarOpen",b);a.element.setAttribute("i-amphtml-sidebar-opened","");Z(a).setAttribute("i-amphtml-sidebar-opened",
"")},350);Ia(a.getAmpDoc(),a.element)}function $a(a,b,c){Z(a).removeAttribute("open");Z(a).removeAttribute("i-amphtml-sidebar-opened");a.mutateElement(function(){Qa(a.element)});a.element.removeAttribute("open");a.element.removeAttribute("i-amphtml-sidebar-opened");Y(a,function(){Q(a.element,!1);Q(Z(a),!1);D(a.element,"owners").schedulePause(a.element,a.getRealChildren());Za(a,"sidebarClose",c)},b?0:350)}
function Va(a,b,c){a.G||(a.G=!0,a.L.enterOverlayMode(),Y(a,function(){return Xa(a,b)}),D(a.getAmpDoc(),"history").push(function(){a.O?X(a,!0,b):X(a,!1,b)}).then(function(b){a.V=b}),c&&(a.ga=c,a.ya=a.L.getScrollTop()))}
function X(a,b,c){if(!a.G)return!1;a.G=!1;a.L.leaveOverlayMode();var d=a.ya==a.L.getScrollTop(),e=a.element.contains(a.C.activeElement);Y(a,function(){return $a(a,b,c)});b&&(Q(a.element,!1),Q(Z(a),!1));-1!=a.V&&(D(a.getAmpDoc(),"history").pop(a.V),a.V=-1);if(a.ga&&e&&d&&(!a.O||!D(a.element,"viewer").isEmbedded()))try{a.ga.focus()}catch(f){}return!0}
function Wa(a,b){if(ja(a.win)["amp-sidebar-swipe-to-dismiss"])ya(b).onGesture(Aa,function(b){b=b.data;b.first?a.ma.startSwipe({swipeElement:a.element,mask:a.Y,direction:"left"==a.H?"backward":"forward",orientation:"horizontal"}):b.last?a.ma.endSwipe(b):a.ma.swipeMove(b)})}function Ra(a,b){return F(a.element,"amp-story")?"left"==b?"right":"left":b}
function Z(a){if(!a.Y){var b=a.C.createElement("div");b.classList.add("i-amphtml-sidebar-mask");b.addEventListener("click",function(){X(a,!1,3)});a.getAmpDoc().getBody().appendChild(b);b.addEventListener("touchmove",function(a){a.preventDefault()});Wa(a,b);a.Y=b}return a.Y}
function Ta(a){a.element.addEventListener("scroll",function(b){a.G&&(1>a.element.scrollTop?(a.element.scrollTop=1,b.preventDefault()):a.element.scrollHeight==a.element.scrollTop+a.element.offsetHeight&&(--a.element.scrollTop,b.preventDefault()))})}function Ya(a){if(!a.qa){var b=a.C.createElement("div");P(b,{height:"54px",width:"100%","background-color":"transparent"});a.element.appendChild(b);a.qa=!0}}
function Za(a,b,c){var d=a.win;var e="amp-sidebar toolbar."+b;var f={};var h={detail:f};Object.assign(h,void 0);"function"==typeof d.CustomEvent?e=new d.CustomEvent(e,h):(d=d.document.createEvent("CustomEvent"),d.initCustomEvent(e,!!h.bubbles,!!h.cancelable,f),e=d);a.U.trigger(a.element,b,e,c)}(function(a){a.registerElement("amp-sidebar",W,"amp-sidebar{--story-page-vh:1vh;position:fixed!important;top:0;max-height:100vh!important;height:100vh;max-width:80vw;background-color:#efefef;min-width:45px!important;outline:none;overflow-x:hidden!important;overflow-y:auto!important;z-index:2147483647;-webkit-overflow-scrolling:touch;will-change:transform}amp-sidebar[side=left]{left:0!important;transform:translateX(-100%);animation-name:i-amphtml-sidebar-slide-out-left}amp-sidebar[side=left][open]{animation-name:i-amphtml-sidebar-slide-in-left}amp-sidebar[side=right]{right:0!important;transform:translateX(100%);animation-name:i-amphtml-sidebar-slide-out-right}amp-sidebar[side=right][open]{animation-name:i-amphtml-sidebar-slide-in-right}amp-sidebar[side][i-amphtml-sidebar-opened]{transform:none;animation:none}.i-amphtml-sidebar-mask,amp-sidebar[side]{animation-duration:233ms;animation-timing-function:cubic-bezier(0,0,.21,1);animation-fill-mode:forwards}.i-amphtml-toolbar>ol,.i-amphtml-toolbar>ul{display:-ms-flexbox;display:flex;-ms-flex-pack:start;justify-content:flex-start;-ms-flex-wrap:wrap;flex-wrap:wrap;overflow:auto;list-style-type:none;padding:0;margin:0}.i-amphtml-sidebar-mask{position:fixed!important;top:0!important;left:0!important;width:100vw!important;height:100vh!important;background-image:none!important;background-color:rgba(0,0,0,0.5);animation-name:i-amphtml-sidebar-mask-fade-out;z-index:2147483646}.i-amphtml-sidebar-mask[open]{animation-name:i-amphtml-sidebar-mask-fade-in}.i-amphtml-sidebar-mask[i-amphtml-sidebar-opened]{animation:none}@keyframes i-amphtml-sidebar-slide-in-left{0%{transform:translateX(-100%)}to{transform:translateX(0)}}@keyframes i-amphtml-sidebar-slide-out-left{0%{transform:translateX(0)}to{transform:translateX(-100%)}}@keyframes i-amphtml-sidebar-slide-in-right{0%{transform:translateX(100%)}to{transform:translateX(0)}}@keyframes i-amphtml-sidebar-slide-out-right{0%{transform:translateX(0)}to{transform:translateX(100%)}}@keyframes i-amphtml-sidebar-mask-fade-in{0%{opacity:0}to{opacity:1}}@keyframes i-amphtml-sidebar-mask-fade-out{0%{opacity:1}to{opacity:0}}\n/*# sourceURL=/extensions/amp-sidebar/0.1/amp-sidebar.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-sidebar-0.1.js.map
